#STRING MATHODE

#MENGGUNAKAN FUNGSION len(),UNTUK MEMCARITAHU BERAPA BANYAK VARIABEL/KARAKTER DALAM STRING
Name = "irfan hafizzurohman"
variabel = len(Name)
print(variabel)

#MENGGUNAKAN METHODE.upper(),UNTUK MENGUBAH SEMUA HURUF YG ADA DALAM TANDA KUTIP2 MENJADI HURUF CAPATIAL
Name = "irfan hafizzurohman"
print(Name.upper())


#MENGGUNAKAN METHODE.lower(),UNTUK MENGUBAH SEMUA HURUF YG ADA DALAM TANDA KUTIP2 MENJADI HURUF KECIL
Name = "MUHAMMAD AZRIL"
print(Name.lower())

#MENGGUNAKAN METHOD.capitalize(),UNTUK MENGUBAH HURUF YG PALING AWAL MENJADI HURUF CAPITAL
Name = "hamzah"
print(Name.capitalize())

#MENGGUNAKAN METHODE.title(),UNTUK MENGUBAH SETIAP HURUF TERDEPAN DARI SETIAP KARAKTER BERUBAH MENJADI HURUF CAPITAL
Name = "putri ayu lestari"
print(Name.title())

#MENGGUNAKAN METHODE.leplace(),UNTUK MENGUBAH SEBUAH KATA DARI SEBUAH STRING MENJADI KATA YANG LAIN
Name = "belajar python dirumah"
print(Name.replace("python" , "javascript"))

#MENGGUNAKAN METHODE.in(),MENCARI APAKAH SEBUAH STRING ITU ADA DALAM SEBUAH STRING YANG LAIN
Name = "Muhammad bagas firmansyah"
message = "bagas"
print(message in Name)