# TUPLE 
#UNTUK TUPLE TIDAK BISA MERUBAH ISI DIDALAM TANDA KURUNG / IMMUTABEL(NILAINYA TIDAK BISA DIUBAH-UBAH)
numbers = (1,2,3,4,5) # SAMA DENGAN LIST[] BEDANYA TUPLE MENGUNAKAN TANDA KURUNG()
print(numbers[0])